name: Build

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-to: type=gha
          cache-from: type=gha
          build-args: |
            NODE_VERSION=${{ matrix.node-version }}

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: "npm"
      # - name: Build binary
      #   run: |
      #     npm i @mapbox/node-pre-gyp node-gyp yarn@latest -g
      #     yarn install --frozen-lockfile
      #     node-pre-gyp build package --build-from-source --fallback-to-build
      # - name: list files
      #   run: ls -lR build/stage/pycabbage/libxmljs/releases/download/
