name: Build

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # node-version: [18]
        node-version: [14, 16, 18, 19]
        arch: [ amd64, arm64v8, arm32v7 ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-to: type=gha
          cache-from: type=gha
          load: true
          tags: libxmljs_builder:latest
          build-args: |
            NODE_VERSION=${{ matrix.node-version }}
            ARCH=${{ matrix.arch }}

      - name: Copy built files from container to host
        run: |
          docker run --name libxmljs_builder_container -d libxmljs_builder:latest
          docker cp libxmljs_builder_container:/dist/ .
          docker stop -t 5 libxmljs_builder_container
          docker rm libxmljs_builder_container

      - name: list files
        run: ls -lR ./dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: node${{ matrix.node-version }}-linux-${{ matrix.arch }}
          path: "dist/**/*.tar.gz"
  build-win-darwin:
    name: Build (win,darwin)
    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16, 18, 19]
        os: [macos-latest, windows-2019]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: cache build
        uses: actions/cache@v3
        with:
          path: ./build/
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock', 'src/**/*', 'vendor/**/*') }}

      - name: Install dependencies
        run: |
          npm i -g yarn@latest
          yarn install

      - name: Build
        run: |
          yarn build
          yarn dist

      - name: copy files
        run: |
          mkdir -p ./dist
          cp -r ./build/stage/pycabbage/libxmljs/releases/download/*/*.tar.gz ./dist/
          ls ./dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: node${{ matrix.node-version }}-${{ matrix.os }}
          path: "dist/**/*.tar.gz"

  publish:
    name: Publish built artifact
    runs-on: ubuntu-latest
    needs: [ build-linux, build-win-darwin ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: .
      - name: list files
        run: ls -lR ./
