name: Build

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-to: type=gha
          cache-from: type=gha
          load: true
          tags: libxmljs_builder:latest
          build-args: |
            NODE_VERSION=${{ matrix.node-version }}

      - name: Copy built files from container to host
        run: |
          docker run --name libxmljs_builder_container -d libxmljs_builder:latest
          docker cp libxmljs_builder_container:/dist/ .
          docker rm libxmljs_builder_container

      - name: list files
        run: ls -lR ./dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: node${{ matrix.node-version }}
          path: "dist/**/*.tar.gz"
